"""Verify exact original CSV reproduction, scientific JSON identity and input provenance."""
from pathlib import Path
import argparse
import ast
import hashlib
import json
import subprocess
import sys

HERE = Path(__file__).resolve().parent
CORE = ("calibration_selected_audit.csv", "calibration_reconstructed_grids.csv", "calibration_grid_summary.csv")


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main(out):
    csv_results = {}
    for name in CORE:
        original, rerun = HERE / "archived" / name, out / name
        matches = original.read_bytes() == rerun.read_bytes()
        assert matches, name
        csv_results[name] = {"byte_identical": matches, "sha256": sha(rerun), "bytes": rerun.stat().st_size}
    original = json.loads((HERE / "archived/calibration_audit.json").read_text())
    rerun = json.loads((out / "calibration_audit.json").read_text())
    scientific = [key for key in original if key not in {"input_hashes", "python", "numpy", "pandas"}]
    assert all(original[key] == rerun[key] for key in scientific)
    assert original["input_hashes"] == rerun["original_audit_input_hashes"]
    manifest = json.loads((HERE / "input/SOURCE_MANIFEST.json").read_text())
    assert all(sha(HERE / entry["path"]) == entry["sha256"] for entry in manifest["files"])
    for path, digest in rerun["input_hashes"].items():
        assert sha(HERE / Path(path.replace("\\", "/"))) == digest
    choose_nodes = []
    for path in (HERE / "archived/check_calibration.py", HERE / "check_calibration.py"):
        tree = ast.parse(path.read_text())
        choose_nodes.append(ast.dump(next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "choose")))
    assert choose_nodes[0] == choose_nodes[1]
    refusal = subprocess.run([sys.executable, str(HERE / "check_calibration.py"), "--out", str(out)],
                             cwd=HERE / "input", capture_output=True, text=True)
    assert refusal.returncode != 0 and "FileExistsError" in refusal.stderr
    assert all(sha(out / name) == entry["sha256"] for name, entry in csv_results.items())
    result = {"status": "passed", "core_csv_results": csv_results,
              "all_original_scientific_json_fields_identical": scientific,
              "original_audit_input_hashes_preserved": True, "all_copied_input_hashes_verified": True,
              "original_selection_function_ast_identical": True,
              "existing_output_directory_refused": True, "existing_results_unchanged_after_refusal": True,
              "portable_run_software": {key: rerun[key] for key in ("python", "numpy", "pandas")},
              "portable_script_sha256": sha(HERE / "check_calibration.py"),
              "output_hashes": {path.name: sha(path) for path in sorted(out.iterdir()) if path.is_file()},
              "not_reconstructed": "Ten fitted-model outer-training inner-OOF grids; ancillary precision-floor activity CSV is preserved, not regenerated by the three-CSV script."}
    (HERE / "PORTABLE_VALIDATION.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=HERE / "out")
    args = parser.parse_args()
    main(args.out.resolve())
